# ---------------------------------------------------------
# PRODUCTION PROFILE (prd)
# ---------------------------------------------------------

# Spring Profile
spring.config.activate.on-profile=prd,prod

# Datasource & Pool (AWS RDS PostgreSQL)
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# JPA & Hibernate
spring.jpa.show-sql=false
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.default_schema=garage

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false
spring.flyway.baseline-version=0
spring.flyway.createSchemas=true
spring.flyway.schemas=garage
spring.flyway.locations=classpath:db/migration

# Security (Keycloak OAuth2 Resource Server via JWKS)
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://keycloak.garage.svc.cluster.local:8080/realms/garage/protocol/openid-connect/certs}

# AWS Messaging (SNS & SQS)
spring.cloud.aws.region.static=${AWS_REGION:us-east-1}
spring.cloud.aws.sns.enabled=${SNS_ENABLED:true}
spring.cloud.aws.sqs.enabled=${SQS_ENABLED:true}
message.notification-creation.topic=${NOTIFICATION_TOPIC:api-garage_notification-creation_topic}
message.notification-creation.queue=${NOTIFICATION_QUEUE:api-garage_notification-creation_queue}

# Observability, APM & OpenTelemetry (New Relic)
management.tracing.enabled=true
management.tracing.sampling.probability=${MANAGEMENT_TRACING_SAMPLING_PROBABILITY:1.0}
management.otlp.tracing.endpoint=${MANAGEMENT_OTLP_TRACING_ENDPOINT:https://otlp.nr-data.net:4318/v1/traces}
management.otlp.tracing.headers.api-key=${NEWRELIC_LICENSE_KEY}
management.otlp.metrics.export.url=${MANAGEMENT_OTLP_METRICS_EXPORT_URL:https://otlp.nr-data.net:4318/v1/metrics}
management.otlp.metrics.export.headers.api-key=${NEWRELIC_LICENSE_KEY}

# Logging
logging.structured.format.console=ecs
logging.include-application-name=true
logging.level.root=INFO
logging.level.br.com.fiap=INFO
logging.level.org.springframework=WARN
logging.level.org.hibernate=INFO
