replicaCount: 1

image:
  repository: api-garage
  tag: latest
  pullPolicy: Never

service:
  type: NodePort
  port: 8080
  nodePort: 30080

env:
  SPRING_PROFILES_ACTIVE: prod


probes:
  enabled: false
  path: /actuator/health
  initialDelaySeconds: 20
  periodSeconds: 10

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 200m
    memory: 768Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  scaleDownStabilizationWindowSeconds: 30

