name: Quality Assurance

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: false

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: ./.github/actions/setup-jdk

      - name: Unit Tests and Code Coverage
        run: mvn -B clean test jacoco:report

      - name: SonarQube Analysis
        if: ${{ secrets.SONAR_TOKEN != '' }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify sonar:sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=$SONAR_TOKEN \
            -Dsonar.qualitygate.wait=false
        continue-on-error: true

  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: ./.github/actions/setup-jdk

      - name: Run integration tests
        run: mvn test -DintegrationTests